FROM rust:1.92-alpine3.23 AS builder

RUN apk add --no-cache \
    build-base \
    alsa-lib-dev

WORKDIR /build
COPY . .

ENV RUSTFLAGS="-C target-feature=-crt-static"
ARG BUILD_FLAGS=--release
ARG BUILD_TYPE=release
RUN --mount=type=cache,target=/usr/local/cargo/registry --mount=type=cache,target=/build/target \
    mkdir /out && \
    cargo build $BUILD_FLAGS -p alsa_pcm_inferno && \
    cp target/$BUILD_TYPE/libasound_module_pcm_inferno.so /out/

FROM alpine:3.23

RUN apk add --no-cache \
    alsa-lib libgcc

COPY --from=builder /out/libasound_module_pcm_inferno.so /usr/lib/alsa-lib/

COPY alsa_pcm_inferno/asoundrc /etc/asound.conf
